### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lazylester**
I tried to follow your instructions, but kept getting "no account exists for this key" message. When I established an account first as my proposed change shows, everything miraculously worked!

### CODE REVIEW

**Comment by elct9620** [comment]
Do you run the `rails generate lets_encrypt:register` to register an account before you try it?

**Comment by lazylester** [comment]
No I didn't run `rails generate lets_encrypt:register`. I don't remember why I didn't do that, but it wasn't clear from the README that this would establish the account at letsencrypt.org. Instead of the change I proposed, perhaps we just need to clarify what `lets_encrypt:register` does... it generates a private key (correct?) and then establishes an account at letsencrypt.org indexed on that key. Is that an accurate description of the generator?

**Comment by elct9620** [comment]
I think we can improve the description of the README.

The private key is required for your Let's Encrypt account to identify which user is using it. If we didn't generate a private key to register an account, it is still unable to call the API and you have to register again for next time.

Reference: https://github.com/elct9620/rails-letsencrypt/blob/master/lib/letsencrypt.rb#L45-L50

**Comment by elct9620** [comment]
Thanks for your help to improve the README 👍

**Pull request merged**
