### PR TITLE
Delete certificate from Redis after model destroy

### PR DESCRIPTION
**Pull request by kirillplatonov**
To keep Redis clean

### CODE REVIEW

**Comment by elct9620** [comment]
How about setting an expiry time when saving to Redis, config for expired after 3 months.

**Comment by kirillplatonov** [comment]
I think with `after_destroy` it's more flexible. It depends on the application. In my case, we have 14 days trial and if user won't pay after the trial we'll remove its account. So keeping certificates for removed accounts for 2.5 months in Redis doesn't make sense. Especially on a large scale.

**Comment by elct9620** [comment]
Ok, that makes sense.

**Comment by kirillplatonov** [comment]
Could you please draft a new release on rubygems?

**Comment by elct9620** [comment]
Ok, let me bump version to 0.9.0

**Pull request merged**
