### PR TITLE
Fix table_name_prefix error on Rails 7.1.3 

### PR DESCRIPTION
**Pull request by tnantoka**
Thank you for the excellent gem! I've been using this for several years and it works great.

I recently updated my app to Rails 7.1.3 and a strange error occurred. I think you can easily reproduce it by following the steps below.

```
$ bundle update --gemfile /app/gemfiles/rails7.gemfile
...
Using activerecord 7.1.3 (was 7.1.1)
...

$ bundle exec appraisal rspec
...
      ActiveRecord::StatementInvalid:
        Could not find table 'lets_encrypt_certificates'
...
32 examples, 24 failures
```

It seems that `table_name_prefix` is not working properly. This may be a Rails issue, but I found that using `table_name` instead would solve the problem. So I created a pull request.

If you don't need this, please feel free to close it.

Thanks,

### CODE REVIEW

**Comment by elct9620** [comment]
It seems the selected Nokogiri version does not support Ruby 2.7 🤔

**Comment by tnantoka** [comment]
@elct9620 
Sorry, I've reverted some unnecessary changes.

**Comment by tnantoka** [comment]
@elct9620 
Thank you for reviewing. I've signed my commits and pushed again.

**Comment by elct9620** [comment]
[v0.11.3](https://github.com/elct9620/rails-letsencrypt/releases/tag/v0.11.3) is released

**Pull request merged**
