### PR TITLE
Do not depend on entire Rails gem.

### LINKED ISSUE #34: Do not depend on the rails gem
It is possible to run Rails without using the entire rails gem, so specifying only required gems such as activesupport, activemodel etc. It would be better if this gem only depended on the required gems from rails.

### PR DESCRIPTION
**Pull request by espen**
Fixes #34

### CODE REVIEW

**Comment by elct9620** [comment]
The test failed, please check it.

**Comment by espen** [comment]
Sorry I have never used Travis before. I updated the Travis Gemfile.lock files now. How can I test this without pushing changes to the PR so that Travis runs? I am still getting an error: "Run `bundle install` elsewhere and add the updated gemfiles/rails_5.gemfile.lock to version control.". I ran `bundle install --gemfile=rails_5.gemfile` and pushed the updated Gemfile.lock.

Running the tests locally works btw.

**Comment by elct9620** [comment]
This gem use [Appraisal](https://github.com/thoughtbot/appraisal) to manage multiple rails version dependency. You need to use it to update all Gemfile.

**Comment by elct9620** [comment]
https://github.com/elct9620/rails-letsencrypt/blob/master/.travis.yml

The Rails 7 support is added but not listed in `.travis.yml` that it didn't be covered by automatic tests.

**Comment by elct9620** [comment]
Seems got some problem due to the bundler version still configured to `1.17.3`, can you help to update it to `2.x`?

**Comment by elct9620** [comment]
The gem dependency has some problems. I think we can drop `2.5` and add `2.7`. `3.0`.

**Comment by espen** [comment]
> Fetching gem metadata from https://rubygems.org/..........
Your bundle is locked to railties (7.0.3.1) from rubygems repository
https://rubygems.org/ or installed locally, but that version can no longer be
found in that source. That means the author of railties (7.0.3.1) has removed
it. You'll need to update your bundle to a version other than railties (7.0.3.1)
that hasn't been removed in order to install.

Ok this is odd. Seems like there is some gem caching issue perhaps? Is it possible to trigger the test again?

**Comment by elct9620** [comment]
I have no idea about it. But you can check for Rails 7 is support Ruby 2.6 or not first 🤔

**Comment by espen** [comment]
Closing in favour for #38 as this was done in my master branch and it doesn't seem possible to update the PR.

**Pull request closed without merging**
